import img01 from "../../../images/img01.jpg";
import img02 from "../../../images/img02.jpeg";
import img03 from "../../../images/img03.jpeg";
import img04 from "../../../images/img04.jpeg";
import img05 from "../../../images/img05.jpeg";
import img06 from "../../../images/img06.jpg";
import img07 from "../../../images/img07.jpeg";
import img08 from "../../../images/img08.jpg";

export const StRecords = [
  {
    id: 1,
    section: "Higher Secondary",
    category: "hs",
    name: "Rakhi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img01,
    status: "active",
  },
  {
    id: 2,
    section: "Higher Secondary",
    category: "hs",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img02,
    status: "active",
  },
  {
    id: 3,
    section: "Higher Secondary",
    category: "hm",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img03,
    status: "active",
  },
  {
    id: 4,
    section: "Higher Secondary",
    category: "hm",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img04,
    status: "active",
  },
  {
    id: 5,
    section: "Higher Secondary",
    category: "cl",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img05,
    status: "active",
  },
  {
    id: 6,
    section: "Higher Secondary",
    category: "cl",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img04,
    status: "active",
  },
  {
    id: 7,
    section: "Higher Secondary",
    category: "hs",
    name: "Rakhi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img01,
    status: "active",
  },
  {
    id: 8,
    section: "Higher Secondary",
    category: "hs",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img02,
    status: "active",
  },
  {
    id: 9,
    section: "Higher Secondary",
    category: "hm",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img03,
    status: "active",
  },
  {
    id: 10,
    section: "Higher Secondary",
    category: "hm",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img04,
    status: "active",
  },
  {
    id: 11,
    section: "Higher Secondary",
    category: "cl",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img05,
    status: "active",
  },
  {
    id: 12,
    section: "Higher Secondary",
    category: "cl",
    name: "Rimi Sarkar",
    fname: "K K Sarkar",
    details: "Reg No: 123, Roll: 0052, No: 11, Year: 2020",
    dtpublish: "15-Feb-2020",
    dtclose: "15-Mar-2024",
    achievement: "First in School",
    imageurl: img04,
    status: "active",
  },
];
